general:
  resource_prefix: # Add your prefix for all resources created
  vpc_id: # Add your vpc id here
  subnet_ids:  # Add your subnet ids here
  security_group_ids: # add your security group
  tags:
    iac: "terraform"
    environment: "rnd"
    project: "airflow-costmos"

lambda:
  lambdaRuntime: python3.13
  test_dag_id: "dbt_version_test"

airflow:
  instance_type: "t3.xlarge"
  ami: "ami-08ec24445ff6d6d96"

  

