general:
  resource_prefix: "cat-rnd-mwaa-dbt"
  vpc_id: "vpc-0dfa99e2ec6455b14"
  # subnet_ids: ["subnet-092e811ee8f19ff4f", "subnet-05ae7fb60603d698b"] # App
  subnet_ids: ["subnet-016e10f06301bd104", "subnet-0c049430ef83c8988"] # Public
  security_group_ids: ["sg-0b5e241790701b30e"]
  tags:
    iac: "terraform"
    environment: "rnd"
    project: "cat-rnd-mwaa-dbt"

lambda:
  lambdaRuntime: python3.13
  test_dag_id: "dbt_version_test"

airflow:
  instance_type: "t3.xlarge"
  ami: "ami-08ec24445ff6d6d96"

  

